name: recsys-autoenc
channels:
- anaconda
- conda-forge
dependencies:
- python=3.6.7
- pandas=0.25.1
- matplotlib=2.2.2
- scipy=1.3.1
- numpy=1.17.0
- seaborn=0.8.1
- scikit-learn=0.21.2
- tqdm=4.33
- requests=2.21.0
- pip
- pip:
  - sagemaker==1.42.2
  - boto3==1.10.20
  - tensorflow-gpu==2.1
