
###

POST https://us-east1-cartola-202712.cloudfunctions.net/recommender HTTP/1.1
content-type: application/json

{
  "user_uuid": "1",
  "watched_movies": [
    1,
    3114,
    87222,
    84944,
    260,
    1196,
    1210,
    2628,
    79006,
    2116,
    7153,
    5952
  ]
}


###

GET http://google.com.br HTTP/1.1
